name: 🔌 Plugin | Package a tag

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Qt lrelease
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qttools5-dev-tools

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6

      - name: Package
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=${{ github.ref_name }}
          qgis-plugin-ci package ${VERSION}
      
#      - name: Upload release assets
#        uses: actions/upload-artifact@v4
#        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
#        with:
#          name: test_plugin.${{ github.ref_name }}
#          path: ./test_plugin.${{ github.ref_name }}.zip
#          if-no-files-found: error
#      
#      - name: Release
#        run: |
#          VERSION=${{ github.ref_name }}
#          qgis-plugin-ci release ${VERSION} \
#          --github-token ${{ secrets.GITHUB_TOKEN }}
