name: 🔌 Plugin | Package a tag

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      plugin_name: test_plugin
      zip_name: ${{ plugin_name }}.0.0.0

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Qt6 lrelease
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qttools5-dev-tools

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6
      
      - name: Create package for intermediate commits (no tag)
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=0.0.0
          qgis-plugin-ci package ${VERSION}

      - name: Fix resources_rc.py Qt import for Qt6 compatibility
        if: ${{ hashFiles('test_plugin/resources_rc.py') != '' }}
        run: >
          unzip ${{zip_name}}.zip -d extracted &&
          sed -i 's/from PyQt5 import QtCore/from qgis.PyQt import QtCore/' extracted/${{ plugin_name }}/resources_rc.py &&
          rm ${{zip_name}}.zip &&
          (cd extracted && zip -r ../${{zip_name}}.zip .) &&
          rm -r extracted
      
      - name: Upload package for intermediate commits (no tag)
        uses: actions/upload-artifact@v4
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{zip_name}}
          path: ./${{zip_name}}.zip
          if-no-files-found: error
#      
#      - name: Release
#        run: |
#          VERSION=${{ github.ref_name }}
#          qgis-plugin-ci release ${VERSION} \
#          --github-token ${{ secrets.GITHUB_TOKEN }}
